WITH RECURSIVE GEN AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT e.ID, e.PARENT_ID, g.GENERATION + 1
    FROM ECOLI_DATA e
    JOIN GEN g
    ON e.PARENT_ID = g.ID
)

SELECT COUNT(GENERATION) AS COUNT, GENERATION
FROM ECOLI_DATA e
JOIN GEN g
ON e.ID = g.ID
LEFT JOIN ECOLI_DATA f
ON e.ID = f.PARENT_ID
WHERE f.ID IS NULL
GROUP BY GENERATION

