# 2022년 4월 13일 취소되지 않은 흉부외과(CS) 진료 예약 내역을 조회하는 SQL
SELECT a.APNT_NO, p.PT_NAME, a.PT_NO, a.MCDP_CD, d.DR_NAME, a.APNT_YMD
FROM APPOINTMENT a
LEFT JOIN PATIENT p
ON a.PT_NO = p.PT_NO
LEFT JOIN DOCTOR d
ON a.MDDR_ID = d.DR_ID
WHERE a.MCDP_CD = 'CS'
AND APNT_YMD > '2022-04-12' AND APNT_YMD < '2022-04-14'
AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD