#fish_type별로 group by하고 MAX(LENGTH)
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO f
JOIN FISH_NAME_INFO n
ON f.FISH_TYPE = n.FISH_TYPE
WHERE LENGTH = (
    SELECT MAX(LENGTH)
    FROM FISH_INFO
    WHERE FISH_TYPE = f.FISH_TYPE)
ORDER BY ID