#FIRST_HALF: SHIPMENT_ID, FLAVOR, TOTAL_ORDER

#ICECREAM_INFO: FLAVOR, INGREDITENT_TYPE

SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF f
LEFT JOIN ICECREAM_INFO i
ON f.FLAVOR = i.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER