SELECT TITLE, b.BOARD_ID, REPLY_ID, r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD b
JOIN USED_GOODS_REPLY r
ON b.BOARD_ID = r.BOARD_ID
WHERE b.CREATED_DATE >= '2022-10-01'
AND b.CREATED_DATE < '2022-11-01'
ORDER BY r.CREATED_DATE, TITLE
#board_id/ contents는 내용 다름